spring:
  jackson:
    defaultPropertyInclusion: "non_null"
  datasource:
    driverClassName: 'org.postgresql.Driver'
    url: jdbc:postgresql://localhost:5433/db
    username: postgres
    password: postgres
  jpa:
    showSql: 'true'
    hibernate:
      ddl-auto: update
    #      ddl-auto: 'create-drop'
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
  servlet:
    multipart:
      max-file-size: 50MB
  kafka:
    bootstrap-servers: localhost:9092

application:
  security:
    jwt:
      secret-key: 4158465a2f6a272c253b4468423246663f3c4a7951673a544c452e2c4d36465c
      expiration: 86400000
  file:
    upload:
      photos-path: ./uploads
